/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sistemabsensi.ui.admin;

import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.Date;
import java.util.LinkedList;
import sistemabsensi.database.Karyawan;
import sistemabsensi.database.RecordAbsen;
import sistemabsensi.database.StatusAbsen;
import sistemabsensi.database.TipeAbsen;
import sistemabsensi.database.admin.DatabaseAdmin;

/**
 *
 * @author rss
 */
public class JPanelMasterDataRecordAbsen extends javax.swing.JPanel {

	private DatabaseAdmin db;

	private String karyawanTerpilih;
	private RecordAbsen recordTerpilih;

	/**
	 * Creates new form JPanelMasterDataRecordAbsen
	 */
	public JPanelMasterDataRecordAbsen(DatabaseAdmin db) {
		this.db = db;
		this.karyawanTerpilih = null;
		this.recordTerpilih = null;
		initComponents();
	}

	public void updateData() {
		try {
			this.tabelData.setModel(this.db.getModelTabel_RecordAbsen());
			this.isiComboBox();
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(-1);
		}
	}

	private void isiComboBoxTipeAbsen() {
		this.comboBoxTipeAbsen.removeAllItems();
		for (TipeAbsen status : TipeAbsen.values()) {
			if (this.recordTerpilih != null && status == this.recordTerpilih.tipe_absen) {
				continue;
			}
			this.comboBoxTipeAbsen.addItem(status);
		}

		if (this.recordTerpilih != null) {
			this.comboBoxTipeAbsen.addItem(this.recordTerpilih.tipe_absen);
			this.comboBoxTipeAbsen.setSelectedItem(this.recordTerpilih.tipe_absen);
		} else {
			this.comboBoxTipeAbsen.setSelectedItem(null);
		}
	}

	private void isiComboBoxStatusAbsen() {
		this.comboBoxStatusAbsen.removeAllItems();
		for (StatusAbsen status : StatusAbsen.values()) {
			if (this.recordTerpilih != null && status == this.recordTerpilih.status_absen) {
				continue;
			}
			this.comboBoxStatusAbsen.addItem(status);
		}

		if (this.recordTerpilih != null) {
			this.comboBoxStatusAbsen.addItem(this.recordTerpilih.status_absen);
			this.comboBoxStatusAbsen.setSelectedItem(this.recordTerpilih.status_absen);
		} else {
			this.comboBoxStatusAbsen.setSelectedItem(null);
		}
	}

	private void isiComboBoxKaryawan() {
		this.comboBoxKaryawan.removeAllItems();

		LinkedList<Karyawan> dataKaryawan = this.db.getDaftarDataKaryawan();
		Karyawan karyawanTerpilih_tmp = null;
		for (Karyawan karyawan : dataKaryawan) {
			if (karyawanTerpilih != null && karyawan.idKaryawan.equals(this.karyawanTerpilih)) {
				karyawanTerpilih_tmp = karyawan;
				continue;
			}
			this.comboBoxKaryawan.addItem(karyawan);
		}

		if (this.karyawanTerpilih != null && karyawanTerpilih_tmp != null) {
			this.comboBoxKaryawan.addItem(karyawanTerpilih_tmp);
			this.comboBoxKaryawan.setSelectedItem(karyawanTerpilih_tmp);
		} else {
			this.comboBoxKaryawan.setSelectedItem(null);
		}

	}

	private static Date toDate(LocalTime localTime) {
		return Date.from(
			localTime.atDate(LocalDate.now())
				.atZone(ZoneId.systemDefault())
				.toInstant()
		);
	}

	private static Date toDate(LocalDate localDate) {
		return Date.from(
			localDate.atStartOfDay()
				.atZone(ZoneId.systemDefault())
				.toInstant()
		);
	}

	private void getDataTerpilih(int idRecord) {

		this.recordTerpilih = db.getRecordAbsenById(idRecord);

		this.karyawanTerpilih = recordTerpilih.id_karyawan;

		Date tanggal = toDate(recordTerpilih.waktu_absen.toLocalDateTime().toLocalDate());
		Date jam = toDate(recordTerpilih.waktu_absen.toLocalDateTime().toLocalTime());
		this.spinnerJam.setValue(jam);
		this.spinnerTanggal.setValue(tanggal);
		this.textAreaCatatanAbsen.setText(this.recordTerpilih.catatan_absen);

		this.isiComboBox();

	}

	private void isiComboBox() {
		this.isiComboBoxKaryawan();
		this.isiComboBoxStatusAbsen();
		this.isiComboBoxTipeAbsen();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel6 = new javax.swing.JPanel();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                comboBoxKaryawan = new javax.swing.JComboBox<>();
                jLabel4 = new javax.swing.JLabel();
                comboBoxTipeAbsen = new javax.swing.JComboBox<>();
                jLabel5 = new javax.swing.JLabel();
                comboBoxStatusAbsen = new javax.swing.JComboBox<>();
                btnHapus = new javax.swing.JButton();
                btnEdit = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                tabelData = new javax.swing.JTable();
                jLabel7 = new javax.swing.JLabel();
                jScrollPane2 = new javax.swing.JScrollPane();
                textAreaCatatanAbsen = new javax.swing.JTextArea();
                jPanel7 = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                spinnerJam = new javax.swing.JSpinner();
                spinnerTanggal = new javax.swing.JSpinner();

                setMaximumSize(new java.awt.Dimension(991, 599));
                setLayout(new java.awt.GridLayout(1, 0));

                jPanel6.setLayout(null);

                jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                jLabel1.setText("KARYAWAN");

                comboBoxKaryawan.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
                comboBoxKaryawan.setModel(new javax.swing.DefaultComboBoxModel<>());

                jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                jLabel4.setText("TIPE ABSEN");

                comboBoxTipeAbsen.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
                comboBoxTipeAbsen.setModel(new javax.swing.DefaultComboBoxModel<>());

                jLabel5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                jLabel5.setText("STATUS ABSEN");

                comboBoxStatusAbsen.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
                comboBoxStatusAbsen.setModel(new javax.swing.DefaultComboBoxModel<>());
                comboBoxStatusAbsen.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                comboBoxStatusAbsenActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(comboBoxTipeAbsen, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(comboBoxStatusAbsen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(comboBoxKaryawan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(comboBoxKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(comboBoxTipeAbsen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(comboBoxStatusAbsen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(24, 24, 24))
                );

                jPanel6.add(jPanel1);
                jPanel1.setBounds(20, 60, 510, 100);

                btnHapus.setBackground(new java.awt.Color(255, 51, 51));
                btnHapus.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                btnHapus.setForeground(new java.awt.Color(0, 0, 0));
                btnHapus.setText("HAPUS");
                btnHapus.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnHapusActionPerformed(evt);
                        }
                });
                jPanel6.add(btnHapus);
                btnHapus.setBounds(430, 480, 90, 30);

                btnEdit.setBackground(new java.awt.Color(255, 255, 102));
                btnEdit.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                btnEdit.setForeground(new java.awt.Color(0, 0, 0));
                btnEdit.setText("EDIT");
                btnEdit.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnEditActionPerformed(evt);
                        }
                });
                jPanel6.add(btnEdit);
                btnEdit.setBounds(10, 470, 76, 30);

                tabelData.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                tabelData.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                tabelData.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tabelDataMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(tabelData);

                jPanel6.add(jScrollPane1);
                jScrollPane1.setBounds(540, 20, 800, 670);

                jLabel7.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                jLabel7.setText("CATATAN ABSEN");
                jPanel6.add(jLabel7);
                jLabel7.setBounds(10, 300, 120, 35);

                textAreaCatatanAbsen.setColumns(20);
                textAreaCatatanAbsen.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
                textAreaCatatanAbsen.setRows(5);
                jScrollPane2.setViewportView(textAreaCatatanAbsen);

                jPanel6.add(jScrollPane2);
                jScrollPane2.setBounds(150, 300, 370, 160);

                javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
                jPanel7.setLayout(jPanel7Layout);
                jPanel7Layout.setHorizontalGroup(
                        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 560, Short.MAX_VALUE)
                );
                jPanel7Layout.setVerticalGroup(
                        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 190, Short.MAX_VALUE)
                );

                jPanel6.add(jPanel7);
                jPanel7.setBounds(780, 510, 560, 190);

                jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                jLabel3.setText("WAKTU ABSEN");
                jPanel6.add(jLabel3);
                jLabel3.setBounds(20, 160, 120, 36);

                jLabel9.setFont(jLabel9.getFont().deriveFont((jLabel9.getFont().getStyle() | java.awt.Font.ITALIC) | java.awt.Font.BOLD, jLabel9.getFont().getSize()+5));
                jLabel9.setText("MAINTENENCE RECORD ABSEN");
                jPanel6.add(jLabel9);
                jLabel9.setBounds(20, 20, 290, 30);

                jLabel8.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                jLabel8.setText("JAM");
                jPanel6.add(jLabel8);
                jLabel8.setBounds(60, 230, 80, 35);

                jLabel6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                jLabel6.setText("TANGGAL");
                jPanel6.add(jLabel6);
                jLabel6.setBounds(60, 190, 80, 35);

                spinnerJam.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
                spinnerJam.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.SECOND));
                spinnerJam.setToolTipText("");
                spinnerJam.setEditor(new javax.swing.JSpinner.DateEditor(spinnerJam, "HH:mm:ss"));
                jPanel6.add(spinnerJam);
                spinnerJam.setBounds(150, 230, 190, 35);

                spinnerTanggal.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
                spinnerTanggal.setModel(new javax.swing.SpinnerDateModel());
                spinnerTanggal.setDoubleBuffered(true);
                spinnerTanggal.setEditor(new javax.swing.JSpinner.DateEditor(spinnerTanggal, "yyyy-MM-dd"));
                jPanel6.add(spinnerTanggal);
                spinnerTanggal.setBounds(150, 190, 190, 35);

                add(jPanel6);
        }// </editor-fold>//GEN-END:initComponents

        private void comboBoxStatusAbsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxStatusAbsenActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_comboBoxStatusAbsenActionPerformed

        private void tabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataMouseClicked
		int barisTerpilih = this.tabelData.getSelectedRow();

		Integer idRecord = (Integer) this.tabelData.getModel().getValueAt(barisTerpilih, 0);

		this.getDataTerpilih(idRecord);

        }//GEN-LAST:event_tabelDataMouseClicked

	private String formatNilaiSpinner() {
		Date tanggal = (Date) this.spinnerTanggal.getValue();
		Date jam = (Date) this.spinnerJam.getValue();
		SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
		return sdf.format(jam);
	}

        private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

		if (this.comboBoxKaryawan.getSelectedItem() == null) {
			this.comboBoxKaryawan.requestFocus();
			DialogPesan.tampilPesan("Tentukan ID Karyawan!");
			return;
		}

		if (this.comboBoxTipeAbsen.getSelectedItem() == null) {
			this.comboBoxTipeAbsen.requestFocus();
			DialogPesan.tampilPesan("Tentukan Tipe Absen");
			return;
		}

		if (this.comboBoxStatusAbsen.getSelectedItem() == null) {
			this.comboBoxStatusAbsen.requestFocus();
			DialogPesan.tampilPesan("Tentukan Status Absen");
		}

		String idKaryawan = ((Karyawan) this.comboBoxKaryawan.getSelectedItem()).idKaryawan;
		StatusAbsen status = (StatusAbsen) this.comboBoxStatusAbsen.getSelectedItem();
		TipeAbsen tipe = (TipeAbsen) this.comboBoxTipeAbsen.getSelectedItem();

		RecordAbsen record = new RecordAbsen();
		if (this.recordTerpilih != null) {
			record.id_recordabsen = this.recordTerpilih.id_recordabsen;
		} else {
			DialogPesan.tampilPesan("Pilihlah satu data record dari tabel!.");
			return;
		}

		record.id_karyawan = idKaryawan;
		record.status_absen = status;
		record.tipe_absen = tipe;
		record.waktu_absen = Timestamp.valueOf(this.formatNilaiSpinner());
		record.catatan_absen = this.textAreaCatatanAbsen.getText();

		this.db.simpanDataRecordAbsen(record);
		this.updateData();

        }//GEN-LAST:event_btnEditActionPerformed

        private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed

		Integer idRecord = null;

		if (this.recordTerpilih != null) {
			idRecord = this.recordTerpilih.id_recordabsen;
		} else {
			DialogPesan.tampilPesan("Pilihlah satu data record dari tabel!.");
			return;
		}

		db.deleteDataRecordAbsen(idRecord);
        }//GEN-LAST:event_btnHapusActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnEdit;
        private javax.swing.JButton btnHapus;
        private javax.swing.JComboBox<Karyawan> comboBoxKaryawan;
        private javax.swing.JComboBox<StatusAbsen> comboBoxStatusAbsen;
        private javax.swing.JComboBox<TipeAbsen> comboBoxTipeAbsen;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JPanel jPanel7;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JSpinner spinnerJam;
        private javax.swing.JSpinner spinnerTanggal;
        private javax.swing.JTable tabelData;
        private javax.swing.JTextArea textAreaCatatanAbsen;
        // End of variables declaration//GEN-END:variables
}
