/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemabsensi.admin.ui;

import java.awt.CardLayout;
import sistemabsensi.admin.data.DBAbsensi;

/**
 *
 * @author rss
 */
public class JFrameAdmin extends javax.swing.JFrame {

	private CardLayout layoutPanel;

	JPanelMasterDataKaryawan MasterDataKaryawan;
	JPanelMasterDataRecordAbsen MasterDataRecordAbsen;
	JPanelMasterDataShift MasterDataShift;

	/**
	 * Creates new form JFrameAdmin
	 */
	public JFrameAdmin() {
		initComponents();
		DBAbsensi db = new DBAbsensi();
		this.MasterDataKaryawan = new JPanelMasterDataKaryawan(db);
		this.MasterDataRecordAbsen = new JPanelMasterDataRecordAbsen(db);
		this.MasterDataShift = new JPanelMasterDataShift(db);
	

		this.jPanelUtama.add("MasterDataKaryawan", this.MasterDataKaryawan);
		this.jPanelUtama.add("MasterDataRecordAbsen", this.MasterDataRecordAbsen);
		this.jPanelUtama.add("MasterDataShift", this.MasterDataShift);
		this.layoutPanel = (CardLayout) this.jPanelUtama.getLayout();

		this.layoutPanel = (CardLayout) this.jPanelUtama.getLayout();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jMenuItem1 = new javax.swing.JMenuItem();
                jMenuBar2 = new javax.swing.JMenuBar();
                jMenu2 = new javax.swing.JMenu();
                jMenu3 = new javax.swing.JMenu();
                jMenuItem2 = new javax.swing.JMenuItem();
                jPanelUtama = new javax.swing.JPanel();
                jMenuBar1 = new javax.swing.JMenuBar();
                jMenu1 = new javax.swing.JMenu();
                jMenu4 = new javax.swing.JMenu();
                jMenuMasterData_Karyawan = new javax.swing.JMenuItem();
                jMenu5 = new javax.swing.JMenu();
                jMenuMasterData_RecordAbsen = new javax.swing.JMenuItem();
                jMenuMasterData_Shift = new javax.swing.JMenuItem();
                jMenuItem3 = new javax.swing.JMenuItem();

                jMenuItem1.setText("jMenuItem1");

                jMenu2.setText("File");
                jMenuBar2.add(jMenu2);

                jMenu3.setText("Edit");
                jMenuBar2.add(jMenu3);

                jMenuItem2.setText("jMenuItem2");

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setMaximumSize(new java.awt.Dimension(1366, 768));
                setMinimumSize(new java.awt.Dimension(1366, 768));
                setPreferredSize(new java.awt.Dimension(1024, 768));
                setResizable(false);
                getContentPane().setLayout(new java.awt.GridLayout(1, 0));

                jPanelUtama.setLayout(new java.awt.CardLayout());
                getContentPane().add(jPanelUtama);

                jMenu1.setText("File");
                jMenuBar1.add(jMenu1);

                jMenu4.setText("Maintenence Karyawan");

                jMenuMasterData_Karyawan.setText("Karyawan");
                jMenuMasterData_Karyawan.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jMenuMasterData_KaryawanActionPerformed(evt);
                        }
                });
                jMenu4.add(jMenuMasterData_Karyawan);

                jMenuBar1.add(jMenu4);

                jMenu5.setText("Maintenence Absensi");

                jMenuMasterData_RecordAbsen.setText("Record Absen");
                jMenuMasterData_RecordAbsen.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jMenuMasterData_RecordAbsenActionPerformed(evt);
                        }
                });
                jMenu5.add(jMenuMasterData_RecordAbsen);

                jMenuMasterData_Shift.setText("Shift");
                jMenuMasterData_Shift.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jMenuMasterData_ShiftActionPerformed(evt);
                        }
                });
                jMenu5.add(jMenuMasterData_Shift);

                jMenuItem3.setText("Laporan Absen");
                jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jMenuItem3ActionPerformed(evt);
                        }
                });
                jMenu5.add(jMenuItem3);

                jMenuBar1.add(jMenu5);

                setJMenuBar(jMenuBar1);

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jMenuMasterData_KaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMasterData_KaryawanActionPerformed
		this.layoutPanel.show(this.jPanelUtama, "MasterDataKaryawan");
		this.MasterDataKaryawan.updateData();
        }//GEN-LAST:event_jMenuMasterData_KaryawanActionPerformed

        private void jMenuMasterData_RecordAbsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMasterData_RecordAbsenActionPerformed
		this.layoutPanel.show(this.jPanelUtama, "MasterDataRecordAbsen");
        }//GEN-LAST:event_jMenuMasterData_RecordAbsenActionPerformed

        private void jMenuMasterData_ShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMasterData_ShiftActionPerformed
		this.layoutPanel.show(this.jPanelUtama, "MasterDataShift");
        }//GEN-LAST:event_jMenuMasterData_ShiftActionPerformed

        private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jMenuItem3ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new JFrameAdmin().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JMenu jMenu1;
        private javax.swing.JMenu jMenu2;
        private javax.swing.JMenu jMenu3;
        private javax.swing.JMenu jMenu4;
        private javax.swing.JMenu jMenu5;
        private javax.swing.JMenuBar jMenuBar1;
        private javax.swing.JMenuBar jMenuBar2;
        private javax.swing.JMenuItem jMenuItem1;
        private javax.swing.JMenuItem jMenuItem2;
        private javax.swing.JMenuItem jMenuItem3;
        private javax.swing.JMenuItem jMenuMasterData_Karyawan;
        private javax.swing.JMenuItem jMenuMasterData_RecordAbsen;
        private javax.swing.JMenuItem jMenuMasterData_Shift;
        private javax.swing.JPanel jPanelUtama;
        // End of variables declaration//GEN-END:variables
}
