/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sistemabsensi.admin.ui;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import sistemabsensi.admin.data.DBAbsensi;
import sistemabsensi.admin.data.Jabatan;

/**
 *
 * @author rss
 */
public class JPanelMasterDataJabatan extends javax.swing.JPanel {

	private DBAbsensi db;

	private Jabatan jabatanTerpilih;
	private final JPanelMasterDataKaryawan panelKaryawan;

	/**
	 * Creates new form JPanelMasterDataShift
	 */
	public JPanelMasterDataJabatan(DBAbsensi db, JPanelMasterDataKaryawan panelKaryawan) {
		this.db = db;
		this.panelKaryawan = panelKaryawan;
		initComponents();
		this.updateData();
	}

	public void updateData() {
		this.panelKaryawan.updateData();
		this.jabatanTerpilih = null;
		this.textFieldNamaJabatan.setText("");
		this.dapatkanData();
	}

	private void dapatkanData() {
		try {
			this.tabelData.setModel(db.getModelTabel_Jabatan());
		} catch (SQLException ex) {
			Logger.getLogger(JPanelMasterDataJabatan.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                tabelData = new javax.swing.JTable();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                textFieldNamaJabatan = new javax.swing.JTextField();
                jPanel2 = new javax.swing.JPanel();
                btnSimpan = new javax.swing.JButton();
                btnHapus = new javax.swing.JButton();

                setMaximumSize(new java.awt.Dimension(991, 599));
                setLayout(null);

                tabelData.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                tabelData.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tabelDataMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(tabelData);

                add(jScrollPane1);
                jScrollPane1.setBounds(20, 130, 710, 190);

                jPanel1.setLayout(new java.awt.GridLayout());

                jLabel1.setText("NAMA JABATAN");
                jPanel1.add(jLabel1);

                textFieldNamaJabatan.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                textFieldNamaJabatanActionPerformed(evt);
                        }
                });
                jPanel1.add(textFieldNamaJabatan);

                add(jPanel1);
                jPanel1.setBounds(30, 20, 700, 40);

                jPanel2.setLayout(new java.awt.GridLayout(1, 2));

                btnSimpan.setText("SIMPAN");
                btnSimpan.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSimpanActionPerformed(evt);
                        }
                });
                jPanel2.add(btnSimpan);

                btnHapus.setText("HAPUS");
                btnHapus.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnHapusActionPerformed(evt);
                        }
                });
                jPanel2.add(btnHapus);

                add(jPanel2);
                jPanel2.setBounds(210, 80, 340, 40);
        }// </editor-fold>//GEN-END:initComponents

        private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
		if (this.textFieldNamaJabatan.getText().isEmpty()) {
			this.textFieldNamaJabatan.requestFocus();
			Pesan.tampilkanPeringatan("Pastikan Field Nama Jabatan Terisi!.");
			return;
		}

		String namaJabatan = this.textFieldNamaJabatan.getText();

		Jabatan jabatan = null;
		if ((this.jabatanTerpilih != null && namaJabatan.equals(this.jabatanTerpilih.namaJabatan)) || (this.jabatanTerpilih == null && this.db.isDataJabatanAda(namaJabatan))) {
			Pesan.tampilkanPeringatan("Tidak ada nilai yang baru atau diubah!.");
			return;
		} else if (this.jabatanTerpilih != null && !namaJabatan.equals(this.jabatanTerpilih.namaJabatan)) {
			jabatan = new Jabatan(this.jabatanTerpilih.idJabatan, namaJabatan);
		} else {
			jabatan = new Jabatan(null, namaJabatan);
		}
		try {

			this.db.simpanDataJabatan(jabatan);
		} catch (SQLException ex) {
			Logger.getLogger(JPanelMasterDataJabatan.class.getName()).log(Level.SEVERE, null, ex);
		}

		this.updateData();

        }//GEN-LAST:event_btnSimpanActionPerformed

        private void textFieldNamaJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNamaJabatanActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_textFieldNamaJabatanActionPerformed

        private void tabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataMouseClicked
		int barisTerpilih = this.tabelData.getSelectedRow();
		String namaJabatan = (String) this.tabelData.getModel().getValueAt(barisTerpilih, 1);
		int idJabatan = Integer.valueOf((String) this.tabelData.getModel().getValueAt(barisTerpilih, 0));

		this.jabatanTerpilih = new Jabatan(idJabatan, namaJabatan);

		this.textFieldNamaJabatan.setText(namaJabatan);
        }//GEN-LAST:event_tabelDataMouseClicked

        private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
		if (this.textFieldNamaJabatan.getText().isEmpty()) {
			this.textFieldNamaJabatan.requestFocus();
			Pesan.tampilkanPeringatan("Pastikan Field Nama Jabatan Terisi!.");
			return;
		}

		String namaJabatan = this.textFieldNamaJabatan.getText();

		Jabatan jabatan = null;
		if (this.jabatanTerpilih != null && namaJabatan.equals(this.jabatanTerpilih.namaJabatan)) {
			jabatan = this.jabatanTerpilih;
		} else if (this.jabatanTerpilih != null && !namaJabatan.equals(this.jabatanTerpilih.namaJabatan)) {
			jabatan = new Jabatan(this.jabatanTerpilih.idJabatan, namaJabatan);
		} else if (this.db.isDataJabatanAda(namaJabatan)) {
			try {
				jabatan = this.db.getDataJabatan(namaJabatan);
			} catch (SQLException ex) {
				Logger.getLogger(JPanelMasterDataJabatan.class.getName()).log(Level.SEVERE, null, ex);
			}
		} else {
			jabatan = new Jabatan(null, namaJabatan);
		}

		if (!Pesan.tampilkanKonfirmasi("Konfirmasi Penghapusan", "Apakah anda yakin ingin menghapus data jabatan: " + namaJabatan + "?. ")) {
			return;
		}

		try {
			this.db.deleteDataJabatan(jabatan.idJabatan);
		} catch (SQLException ex) {
			Logger.getLogger(JPanelMasterDataJabatan.class.getName()).log(Level.SEVERE, null, ex);
		}

		this.updateData();
        }//GEN-LAST:event_btnHapusActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnHapus;
        private javax.swing.JButton btnSimpan;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable tabelData;
        private javax.swing.JTextField textFieldNamaJabatan;
        // End of variables declaration//GEN-END:variables
}
