/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sistemabsensi.admin.ui;

/**
 *
 * @author rss
 */
public class JPanelLogAbsenTerkini extends javax.swing.JPanel {

	/**
	 * Creates new form JPanelHistoriAbsensi
	 */
	public JPanelLogAbsenTerkini() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane4 = new javax.swing.JScrollPane();
                jTextArea2 = new javax.swing.JTextArea();

                setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jTextArea2.setColumns(20);
                jTextArea2.setRows(5);
                jScrollPane4.setViewportView(jTextArea2);

                add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 640, 520));
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JScrollPane jScrollPane4;
        private javax.swing.JTextArea jTextArea2;
        // End of variables declaration//GEN-END:variables
}
