/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sistemabsensi.admin.ui;

import sistemabsensi.admin.database.DatabaseAdmin;
import sistemabsensi.admin.database.Jabatan;

/**
 *
 * @author rss
 */
public class JPanelMasterDataJabatan extends javax.swing.JPanel {

	private DatabaseAdmin db;

	private Jabatan jabatanTerpilih;
	private final JPanelMasterDataKaryawan panelKaryawan;

	/**
	 * Creates new form JPanelMasterDataShift
	 */
	public JPanelMasterDataJabatan(DatabaseAdmin db, JPanelMasterDataKaryawan panelKaryawan) {
		this.db = db;
		this.panelKaryawan = panelKaryawan;
		initComponents();
		this.updateData();
	}

	public void updateData() {
		this.panelKaryawan.updateData();
		this.jabatanTerpilih = null;
		this.textFieldNamaJabatan.setText("");
		this.dapatkanData();
	}

	private void dapatkanData() {
		this.tabelData.setModel(db.getModelTabel_Jabatan());

	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                tabelData = new javax.swing.JTable();
                jLabel1 = new javax.swing.JLabel();
                textFieldNamaJabatan = new javax.swing.JTextField();
                btnHapus = new javax.swing.JButton();
                btnSimpan = new javax.swing.JButton();
                jLabel2 = new javax.swing.JLabel();

                setBorder(javax.swing.BorderFactory.createEtchedBorder());
                setMaximumSize(new java.awt.Dimension(991, 599));

                tabelData.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                tabelData.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                tabelData.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                tabelData.setShowGrid(true);
                tabelData.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tabelDataMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(tabelData);

                jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                jLabel1.setText("NAMA JABATAN");

                textFieldNamaJabatan.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                textFieldNamaJabatan.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                textFieldNamaJabatanActionPerformed(evt);
                        }
                });

                btnHapus.setBackground(new java.awt.Color(255, 51, 51));
                btnHapus.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                btnHapus.setForeground(new java.awt.Color(0, 0, 0));
                btnHapus.setText("HAPUS");
                btnHapus.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnHapusActionPerformed(evt);
                        }
                });

                btnSimpan.setBackground(new java.awt.Color(153, 255, 153));
                btnSimpan.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                btnSimpan.setForeground(new java.awt.Color(0, 0, 0));
                btnSimpan.setText("SIMPAN");
                btnSimpan.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSimpanActionPerformed(evt);
                        }
                });

                jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
                jLabel2.setText("Master Data Jabatan");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(textFieldNamaJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jLabel2))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textFieldNamaJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSimpan)
                                        .addComponent(btnHapus)))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
		if (this.textFieldNamaJabatan.getText().isEmpty()) {
			this.textFieldNamaJabatan.requestFocus();
			DialogPesan.tampilPesan("Pastikan Field Nama Jabatan Terisi!.");
			return;
		}

		final String namaJabatan = this.textFieldNamaJabatan.getText();

		// cek jika ada perubahan data di form input.
		if ((this.jabatanTerpilih != null && namaJabatan.equals(this.jabatanTerpilih.namaJabatan))
			|| (this.jabatanTerpilih == null && this.db.isDataJabatanAda(namaJabatan))) {
			DialogPesan.tampilPesan("Data Sudah Ada!.");
			return;
		}

		Jabatan jabatan = new Jabatan(null, namaJabatan);

		// gunakan id data jabatan yang user pilih jika ada
		// menandakan operasi (UPDATE)
		if (this.jabatanTerpilih != null && !namaJabatan.equals(this.jabatanTerpilih.namaJabatan)) {
			jabatan.idJabatan = jabatanTerpilih.idJabatan;
		}

		this.db.simpanDataJabatan(jabatan);

		this.updateData();

        }//GEN-LAST:event_btnSimpanActionPerformed

        private void textFieldNamaJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNamaJabatanActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_textFieldNamaJabatanActionPerformed

        private void tabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataMouseClicked
		int barisTerpilih = this.tabelData.getSelectedRow();
		String namaJabatan = (String) this.tabelData.getModel().getValueAt(barisTerpilih, 1);
		int idJabatan = Integer.valueOf((String) this.tabelData.getModel().getValueAt(barisTerpilih, 0));

		this.jabatanTerpilih = new Jabatan(idJabatan, namaJabatan);

		this.textFieldNamaJabatan.setText(namaJabatan);
        }//GEN-LAST:event_tabelDataMouseClicked

        private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed

		// Pastikan field input terisi.
		if (this.textFieldNamaJabatan.getText().isEmpty()) {
			this.textFieldNamaJabatan.requestFocus();
			DialogPesan.tampilPesan("Pastikan Field Nama Jabatan Terisi!.");
			return;
		}

		final String namaJabatan = this.textFieldNamaJabatan.getText();

		Integer idJabatan = null;

		if (this.jabatanTerpilih != null && this.jabatanTerpilih.namaJabatan.equals(namaJabatan)) {
			idJabatan = this.jabatanTerpilih.idJabatan;
		} else if (this.db.isDataJabatanAda(namaJabatan)) {
			final Jabatan jabatan = this.db.getDataJabatan(namaJabatan);
			if (jabatan == null) {
				System.err.println("Gagal Mendapatkan data Jabatan");
				System.exit(-1);
			}
			idJabatan = jabatan.idJabatan;
		} else {
			DialogPesan.tampilPesan("Tidak ada Data Jabatan Yang Sesuai untuk Dihapus, pastikan data jabatan sudah ada di database!");
			return;
		}

		if (idJabatan == null) {
			System.err.println("Gagal Mendapatkan id data Jabatan");
			System.exit(-1);
		}

		if (!DialogPesan.tampilKonfirmasi("Konfirmasi Penghapusan", "Apakah anda yakin ingin menghapus data jabatan: " + namaJabatan + "?. ")) {
			return; // cancel
		}
		this.db.deleteDataJabatan(idJabatan);

		this.updateData();
        }//GEN-LAST:event_btnHapusActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnHapus;
        private javax.swing.JButton btnSimpan;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable tabelData;
        private javax.swing.JTextField textFieldNamaJabatan;
        // End of variables declaration//GEN-END:variables
}
