/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sistemabsensi.admin.ui;

import java.awt.event.ActionEvent;
import sistemabsensi.admin.data.DBAbsensi;
import sistemabsensi.admin.data.StatusLogin;

/**
 *
 * @author rss
 */
public class JPanelLoginAdmin extends javax.swing.JPanel {

	DBAbsensi db;
	JFrameAdmin frameAdmin;

	/**
	 * Creates new form JPanelLogin
	 */
	public JPanelLoginAdmin(DBAbsensi db, JFrameAdmin frameAdmin) {
		this.db = db;
		this.frameAdmin = frameAdmin;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                textFieldID = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                textFieldPassword = new javax.swing.JPasswordField();
                jLabel1 = new javax.swing.JLabel();
                btnLogin = new javax.swing.JButton();

                setName("Form"); // NOI18N

                jPanel1.setName("jPanel1"); // NOI18N

                jPanel2.setName("jPanel2"); // NOI18N

                jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                jLabel2.setText("ID");
                jLabel2.setName("jLabel2"); // NOI18N

                textFieldID.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                textFieldID.setName("textFieldID"); // NOI18N

                jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                jLabel3.setText("PASSWORD");
                jLabel3.setName("jLabel3"); // NOI18N

                textFieldPassword.setName("textFieldPassword"); // NOI18N

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textFieldID)
                                        .addComponent(textFieldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE))
                                .addGap(99, 99, 99))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(textFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                );

                jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
                jLabel1.setText("LOGIN ADMIN");
                jLabel1.setName("jLabel1"); // NOI18N

                btnLogin.setText("LOGIN");
                btnLogin.setName("btnLogin"); // NOI18N
                btnLogin.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnLoginActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(15, 15, 15))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(119, 119, 119))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(227, 227, 227)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(12, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(409, 409, 409)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(415, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(291, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(275, 275, 275))
                );
        }// </editor-fold>//GEN-END:initComponents

	private void clearField() {
		this.textFieldID.setText("");
		this.textFieldPassword.setText("");
	}

        private void btnLoginActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
		if (this.textFieldID.getText().isEmpty()) {
			this.textFieldID.requestFocus();
			Pesan.tampilkanPeringatan("ID masih Home!");
			return;
		} else if (this.textFieldPassword.getText().isBlank()) {
			this.textFieldPassword.requestFocus();
			Pesan.tampilkanPeringatan("Password masih Home!");
			return;
		} else {
			String id = this.textFieldID.getText();
			String password = this.textFieldPassword.getText();

			StatusLogin status = db.loginAdminValid(id, password);
			switch (status) {
				case LOGIN_VALID:
					Pesan.tampilkanPeringatan("SELAMAT DATANG");
					this.frameAdmin.admin_terlogin = true;
					break;
				case PASSWORD_SALAH:
					Pesan.tampilkanPeringatan("Password Salah!.");
					this.clearField();
					break;
				case ID_TIDAK_TERDAFTAR:
					Pesan.tampilkanPeringatan("Anda Tidak Terdaftar Sebagai Admin!.");
					break;
			}
		}
        }//GEN-LAST:event_btnLoginActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        javax.swing.JButton btnLogin;
        javax.swing.JLabel jLabel1;
        javax.swing.JLabel jLabel2;
        javax.swing.JLabel jLabel3;
        javax.swing.JPanel jPanel1;
        javax.swing.JPanel jPanel2;
        javax.swing.JTextField textFieldID;
        javax.swing.JPasswordField textFieldPassword;
        // End of variables declaration//GEN-END:variables
}
