/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sistemabsensi.user.ui;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import sistemabsensi.user.data.DBAbsensi;
import sistemabsensi.user.data.Karyawan;

/**
 *
 * @author rss
 */
public class JPanelLogin extends javax.swing.JPanel{

	private JFrameAbsensi frameAbsensi;
	private DBAbsensi dbAbsensi;
	
	/**
	 * Creates new form LoginScreen
	 */
	public JPanelLogin(JFrameAbsensi frameAbsensi) {
		this.frameAbsensi = frameAbsensi;
		this.dbAbsensi = frameAbsensi.getDB();
		initComponents();
	}
	
	private void tampilkanDialog(String msg) {
		JOptionPane.showMessageDialog(frameAbsensi, msg);
	}
	
	public void resetInputBox() {
		this.textFieldID.setText("");
		this.fieldPassword.setText("");
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jInternalFrame1 = new javax.swing.JInternalFrame();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jLabel4 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                btnLogin = new javax.swing.JButton();
                textFieldID = new javax.swing.JTextField();
                fieldPassword = new javax.swing.JPasswordField();

                jInternalFrame1.setVisible(true);

                javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
                jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
                jInternalFrame1Layout.setHorizontalGroup(
                        jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jInternalFrame1Layout.setVerticalGroup(
                        jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jScrollPane1.setViewportView(jTable1);

                setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

                jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
                jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
                jPanel1.setLayout(null);

                jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

                jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
                jLabel4.setText("PASSWORD");

                jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
                jLabel3.setText("ID");

                btnLogin.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
                btnLogin.setText("LOGIN");
                btnLogin.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnLoginActionPerformed(evt);
                        }
                });

                textFieldID.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
                textFieldID.setMinimumSize(new java.awt.Dimension(150, 25));
                textFieldID.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                textFieldIDActionPerformed(evt);
                        }
                });

                fieldPassword.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnLogin)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(fieldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                                        .addComponent(textFieldID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap(57, Short.MAX_VALUE))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textFieldID, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fieldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLogin)
                                .addContainerGap(12, Short.MAX_VALUE))
                );

                jPanel1.add(jPanel2);
                jPanel2.setBounds(210, 200, 390, 170);

                add(jPanel1);
        }// </editor-fold>//GEN-END:initComponents

	//---------------------------------------------------------------------//
	// Event tombol login ditekan                                          //
	//---------------------------------------------------------------------//
	
        private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

                if (fieldPassword.getText().isEmpty() && textFieldID.getText().isEmpty()) {
                        tampilkanDialog("Masukan ID dan Password!");
                        textFieldID.requestFocus();
                } else if (fieldPassword.getText().isEmpty()) {
                        tampilkanDialog("Masukan Password!");
                        fieldPassword.requestFocus();
                } else if (textFieldID.getText().isEmpty()) {
                        tampilkanDialog("Masukan ID!");
                        textFieldID.requestFocus();
                } else { // jika field password dan id sudah valid

                        final String idKaryawan = textFieldID.getText();
                        final String password = fieldPassword.getText();

                        // TODO: cek role user
			// cek jika data karyawan yang memiliki id yg diinput ada di database.
                        if (dbAbsensi.isDataKaryawanAda(idKaryawan)) {
                                try {
					
                                        Karyawan karyawan = dbAbsensi.getDataKaryawan(idKaryawan);

                                        if (karyawan.getRole() == null) {
                                                tampilkanDialog("Pastikan anda telah terdaftar sebagai karyawan!");
                                                fieldPassword.setText("");
                                                textFieldID.setText("");
						return;
                                        } else if (dbAbsensi.isKaryawanTerlogin(idKaryawan)) {
						tampilkanDialog("Anda memiliki sesi login yang aktif di sistem absensi");
                                                fieldPassword.setText("");
                                                textFieldID.setText("");
						return;
					}
					
					if (karyawan.getPassword().equals(password)) { // jika password sesuai
						// karyawan yang absen disimpan
                                                this.frameAbsensi.setKaryawan(karyawan);
						
						this.dbAbsensi.tandaiKaryawanSedangLogin(idKaryawan);
						
						// buka tampilan absen
                                                this.frameAbsensi.bukaPanelAbsen();
                                        } else {                                       // jika password salah
                                                tampilkanDialog("Password Salah!");
                                                fieldPassword.setText("");
                                                fieldPassword.requestFocus();
                                        }
					
					
                                } catch (SQLException e) {
                                        e.printStackTrace();
                                        System.exit(-1);
                                }
				
                        } else { // keluar jika tidak terdaftar
                                tampilkanDialog("Pastikan anda telah terdaftar sebagai karyawan!");
                                fieldPassword.setText("");
                                textFieldID.setText("");
                        }
                }
        }//GEN-LAST:event_btnLoginActionPerformed

        private void textFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldIDActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_textFieldIDActionPerformed

	

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnLogin;
        private javax.swing.JPasswordField fieldPassword;
        private javax.swing.JInternalFrame jInternalFrame1;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable jTable1;
        private javax.swing.JTextField textFieldID;
        // End of variables declaration//GEN-END:variables

}
