/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemabsensi.ui;

import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import sistemabsensi.ui.admin.database.DatabaseAdmin;
import sistemabsensi.ui.admin.ui.DialogPesan;
import sistemabsensi.ui.admin.ui.JPanelCetakLaporan;
import sistemabsensi.ui.admin.ui.JPanelLoginAdmin;
import sistemabsensi.ui.admin.ui.JPanelMasterDataKaryawan;
import sistemabsensi.ui.admin.ui.JPanelMasterDataRecordAbsen;
import sistemabsensi.ui.admin.ui.JPanelMasterDataShift;
import sistemabsensi.ui.admin.ui.JPanelWelcome;
import sistemabsensi.ui.absensi.ui.JPanelAbsen;

/**
 *
 * @author rss
 */
public class JFrameUtama extends javax.swing.JFrame {

	private CardLayout layoutPanel;

	JPanelMasterDataKaryawan MasterDataKaryawan;
	JPanelMasterDataRecordAbsen MasterDataRecordAbsen;
	JPanelMasterDataShift MasterDataShift;
	JPanelLoginAdmin panelLogin;
	JPanelWelcome panelWelcome;
	JPanelCetakLaporan panelLaporan;
	
	public boolean admin_terlogin = false;

	/**
	 * Creates new form JFrameAdmin
	 */
	public JFrameUtama() {
		
		DatabaseAdmin db = new DatabaseAdmin();
		initComponents();

		this.MasterDataKaryawan = new JPanelMasterDataKaryawan(db);
		this.MasterDataRecordAbsen = new JPanelMasterDataRecordAbsen(db);
		this.MasterDataShift = new JPanelMasterDataShift(db);
		this.panelLogin = new JPanelLoginAdmin(db, this);
		this.panelWelcome = new JPanelWelcome(this);
		this.panelLaporan = new JPanelCetakLaporan(db);

		this.jPanelUtama.add("Home", this.panelWelcome);
		this.jPanelUtama.add("MasterDataKaryawan", this.MasterDataKaryawan);
		this.jPanelUtama.add("MasterDataRecordAbsen", this.MasterDataRecordAbsen);
		this.jPanelUtama.add("MasterDataShift", this.MasterDataShift);
		this.jPanelUtama.add("Login", this.panelLogin);
		this.jPanelUtama.add("Laporan", this.panelLaporan);
		
		this.layoutPanel = (CardLayout) this.jPanelUtama.getLayout();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jMenuItem1 = new javax.swing.JMenuItem();
                jMenuBar2 = new javax.swing.JMenuBar();
                jMenu2 = new javax.swing.JMenu();
                jMenu3 = new javax.swing.JMenu();
                jMenuItem2 = new javax.swing.JMenuItem();
                jPanel1 = new javax.swing.JPanel();
                jPanelUtama = new javax.swing.JPanel();
                jMenuBar1 = new javax.swing.JMenuBar();
                jMenu1 = new javax.swing.JMenu();
                bukaLoginAdmin = new javax.swing.JMenuItem();
                bukaTampilanAbsen = new javax.swing.JMenuItem();
                menuBtnLogout = new javax.swing.JMenuItem();
                bukaHome = new javax.swing.JMenuItem();
                exitAplikasi = new javax.swing.JMenuItem();
                jMenu4 = new javax.swing.JMenu();
                jMenuMasterData_Karyawan = new javax.swing.JMenuItem();
                jMenu5 = new javax.swing.JMenu();
                jMenuMasterData_RecordAbsen = new javax.swing.JMenuItem();
                jMenuMasterData_Shift = new javax.swing.JMenuItem();
                jMenuItem3 = new javax.swing.JMenuItem();

                jMenuItem1.setText("jMenuItem1");

                jMenu2.setText("File");
                jMenuBar2.add(jMenu2);

                jMenu3.setText("Edit");
                jMenuBar2.add(jMenu3);

                jMenuItem2.setText("jMenuItem2");

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setMinimumSize(new java.awt.Dimension(1366, 768));
                setResizable(false);
                getContentPane().setLayout(new java.awt.GridLayout(1, 0));

                jPanelUtama.setLayout(new java.awt.CardLayout());
                getContentPane().add(jPanelUtama);

                jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jMenuBar1.setFont(jMenuBar1.getFont().deriveFont(jMenuBar1.getFont().getStyle() | java.awt.Font.BOLD));

                jMenu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                jMenu1.setText("File");

                bukaLoginAdmin.setText("Login Admin");
                bukaLoginAdmin.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bukaLoginAdminActionPerformed(evt);
                        }
                });
                jMenu1.add(bukaLoginAdmin);

                bukaTampilanAbsen.setText("Absensi");
                bukaTampilanAbsen.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bukaTampilanAbsenActionPerformed(evt);
                        }
                });
                jMenu1.add(bukaTampilanAbsen);

                menuBtnLogout.setText("Logout");
                menuBtnLogout.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                menuBtnLogoutActionPerformed(evt);
                        }
                });
                jMenu1.add(menuBtnLogout);

                bukaHome.setText("Home");
                bukaHome.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bukaHomeActionPerformed(evt);
                        }
                });
                jMenu1.add(bukaHome);

                exitAplikasi.setText("Exit");
                exitAplikasi.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                exitAplikasiActionPerformed(evt);
                        }
                });
                jMenu1.add(exitAplikasi);

                jMenuBar1.add(jMenu1);

                jMenu4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                jMenu4.setText("Maintenence Karyawan");

                jMenuMasterData_Karyawan.setText("Karyawan");
                jMenuMasterData_Karyawan.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jMenuMasterData_KaryawanActionPerformed(evt);
                        }
                });
                jMenu4.add(jMenuMasterData_Karyawan);

                jMenuBar1.add(jMenu4);

                jMenu5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                jMenu5.setText("Maintenence Absensi");

                jMenuMasterData_RecordAbsen.setText("Record Absen");
                jMenuMasterData_RecordAbsen.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jMenuMasterData_RecordAbsenActionPerformed(evt);
                        }
                });
                jMenu5.add(jMenuMasterData_RecordAbsen);

                jMenuMasterData_Shift.setText("Shift");
                jMenuMasterData_Shift.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jMenuMasterData_ShiftActionPerformed(evt);
                        }
                });
                jMenu5.add(jMenuMasterData_Shift);

                jMenuItem3.setText("Cetak Laporan");
                jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jMenuItem3ActionPerformed(evt);
                        }
                });
                jMenu5.add(jMenuItem3);

                jMenuBar1.add(jMenu5);

                setJMenuBar(jMenuBar1);

                pack();
        }// </editor-fold>//GEN-END:initComponents
	
        private void jMenuMasterData_KaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMasterData_KaryawanActionPerformed
		if (!this.admin_terlogin) {
			DialogPesan.tampilPesan("Login Terlebih Dahulu Jika ingin mengakses data!.");
			this.layoutPanel.show(this.jPanelUtama, "Login");
			return;
		}
		this.layoutPanel.show(this.jPanelUtama, "MasterDataKaryawan");
		this.MasterDataKaryawan.updateData();
        }//GEN-LAST:event_jMenuMasterData_KaryawanActionPerformed

        private void jMenuMasterData_RecordAbsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMasterData_RecordAbsenActionPerformed
		if (!this.admin_terlogin) {
			DialogPesan.tampilPesan("Login Terlebih Dahulu Jika ingin mengakses data!.");
			this.layoutPanel.show(this.jPanelUtama, "Login");
			return;
		}
		this.layoutPanel.show(this.jPanelUtama, "MasterDataRecordAbsen");
		this.MasterDataRecordAbsen.updateData();
        }//GEN-LAST:event_jMenuMasterData_RecordAbsenActionPerformed

        private void jMenuMasterData_ShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMasterData_ShiftActionPerformed
		if (!this.admin_terlogin) {
			DialogPesan.tampilPesan("Login Terlebih Dahulu Jika ingin mengakses data!.");
			this.layoutPanel.show(this.jPanelUtama, "Login");
			return;
		}
		this.layoutPanel.show(this.jPanelUtama, "MasterDataShift");
		this.MasterDataShift.updateData();
        }//GEN-LAST:event_jMenuMasterData_ShiftActionPerformed

        private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
                if (!this.admin_terlogin) {
			DialogPesan.tampilPesan("Login Terlebih Dahulu Jika ingin mengakses data!.");
			this.layoutPanel.show(this.jPanelUtama, "Login");
			return;
		}
		this.layoutPanel.show(this.jPanelUtama, "Laporan");
		this.panelLaporan.updateData();// TODO add your handling code here:
        }//GEN-LAST:event_jMenuItem3ActionPerformed

	public void bukaLoginAdmin() {
		this.layoutPanel.show(this.jPanelUtama, "Login");
	}
	
        private void bukaLoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bukaLoginAdminActionPerformed
                this.bukaLoginAdmin();
        }//GEN-LAST:event_bukaLoginAdminActionPerformed

        private void menuBtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBtnLogoutActionPerformed
                if(this.admin_terlogin) {
			DialogPesan.tampilPesan("Anda Terlogout");
			this.layoutPanel.show(this.jPanelUtama, "Home");
			this.admin_terlogin = false;
		}
		
        }//GEN-LAST:event_menuBtnLogoutActionPerformed

	public void bukaTampilanAbsen() {
		JFrame frame = new JFrame();
		frame.setSize(800,600);
		JPanel panel = new JPanelAbsen();
		panel.setVisible(true);
		frame.add(panel);
		frame.setVisible(true);
	}
	
        private void bukaTampilanAbsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bukaTampilanAbsenActionPerformed
		this.bukaTampilanAbsen();
        }//GEN-LAST:event_bukaTampilanAbsenActionPerformed

        private void bukaHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bukaHomeActionPerformed
                this.layoutPanel.show(this.jPanelUtama, "Home");
        }//GEN-LAST:event_bukaHomeActionPerformed

        private void exitAplikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitAplikasiActionPerformed
                System.exit(0);
        }//GEN-LAST:event_exitAplikasiActionPerformed

	public void bukaMaintenenceKaryawan() {
		if (!this.admin_terlogin) {
			DialogPesan.tampilPesan("Login Terlebih Dahulu Jika ingin mengakses data!.");
			this.layoutPanel.show(this.jPanelUtama, "Login");
			return;
		}
		this.layoutPanel.show(this.jPanelUtama, "MasterDataKaryawan");
		this.MasterDataKaryawan.updateData();
	}
	/**
	 * @param args the command line arguments
	 */
	

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JMenuItem bukaHome;
        private javax.swing.JMenuItem bukaLoginAdmin;
        private javax.swing.JMenuItem bukaTampilanAbsen;
        private javax.swing.JMenuItem exitAplikasi;
        private javax.swing.JMenu jMenu1;
        private javax.swing.JMenu jMenu2;
        private javax.swing.JMenu jMenu3;
        private javax.swing.JMenu jMenu4;
        private javax.swing.JMenu jMenu5;
        private javax.swing.JMenuBar jMenuBar1;
        private javax.swing.JMenuBar jMenuBar2;
        private javax.swing.JMenuItem jMenuItem1;
        private javax.swing.JMenuItem jMenuItem2;
        private javax.swing.JMenuItem jMenuItem3;
        private javax.swing.JMenuItem jMenuMasterData_Karyawan;
        private javax.swing.JMenuItem jMenuMasterData_RecordAbsen;
        private javax.swing.JMenuItem jMenuMasterData_Shift;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanelUtama;
        private javax.swing.JMenuItem menuBtnLogout;
        // End of variables declaration//GEN-END:variables
}
