/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sistemabsensi.ui.admin.ui;

import java.awt.event.ActionEvent;
import sistemabsensi.ui.JFrameUtama;
import sistemabsensi.ui.admin.database.DatabaseAdmin;
import sistemabsensi.ui.admin.database.StatusLogin;

/**
 *
 * @author rss
 */
public class JPanelLoginAdmin extends javax.swing.JPanel {

	private DatabaseAdmin db;
	private JFrameUtama frameAdmin;

	/**
	 * Creates new form JPanelLogin
	 */
	public JPanelLoginAdmin(DatabaseAdmin db, JFrameUtama frameAdmin) {
		this.db = db;
		this.frameAdmin = frameAdmin;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                textFieldID = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                textFieldPassword = new javax.swing.JPasswordField();
                btnLogin = new javax.swing.JButton();

                setName("Form"); // NOI18N

                jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login Admin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 0, 24))); // NOI18N
                jPanel1.setName("jPanel1"); // NOI18N

                jPanel2.setName("jPanel2"); // NOI18N

                jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
                jLabel2.setText("ID");
                jLabel2.setName("jLabel2"); // NOI18N

                textFieldID.setFont(textFieldID.getFont().deriveFont(textFieldID.getFont().getSize()+5f));
                textFieldID.setName("textFieldID"); // NOI18N

                jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
                jLabel3.setText("PASSWORD");
                jLabel3.setName("jLabel3"); // NOI18N

                textFieldPassword.setFont(textFieldPassword.getFont().deriveFont(textFieldPassword.getFont().getSize()+5f));
                textFieldPassword.setName("textFieldPassword"); // NOI18N

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textFieldID)
                                        .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(textFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                );

                btnLogin.setBackground(new java.awt.Color(153, 153, 255));
                btnLogin.setFont(btnLogin.getFont().deriveFont(btnLogin.getFont().getStyle() | java.awt.Font.BOLD, btnLogin.getFont().getSize()+11));
                btnLogin.setText("LOGIN");
                btnLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
                btnLogin.setName("btnLogin"); // NOI18N
                btnLogin.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnLoginActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(15, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(15, 15, 15))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(25, 25, 25))))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(410, 410, 410)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(397, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(302, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(295, 295, 295))
                );
        }// </editor-fold>//GEN-END:initComponents

	private void clearField() {
		this.textFieldID.setText("");
		this.textFieldPassword.setText("");
	}

        private void btnLoginActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
		if (this.textFieldID.getText().isEmpty()) {
			this.textFieldID.requestFocus();
			DialogPesan.tampilPesan("ID masih Home!");
			return;
		} else if (this.textFieldPassword.getText().isBlank()) {
			this.textFieldPassword.requestFocus();
			DialogPesan.tampilPesan("Password masih Home!");
			return;
		} else {
			final String id = this.textFieldID.getText();
			final String password = this.textFieldPassword.getText();

			final StatusLogin status = db.loginAdminValid(id, password);
			
			assert(status != null);
			
			switch (status) {
				case LOGIN_VALID: {
					
					final String namaKaryawan = this.db.getNamaKaryawan(id);
					
					assert (namaKaryawan != null);
					
					if (namaKaryawan != null)
						DialogPesan.tampilPesan("SELAMAT DATANG, " + namaKaryawan);
					
					this.frameAdmin.admin_terlogin = true;
					
					this.frameAdmin.bukaMaintenenceKaryawan();
				}break;
				case PASSWORD_SALAH:
					DialogPesan.tampilPesan("Password Salah!.");
					this.clearField();
					break;
				case ID_TIDAK_TERDAFTAR:
					DialogPesan.tampilPesan("Anda Tidak Terdaftar Sebagai Admin!.");
					break;
			}
		}
        }//GEN-LAST:event_btnLoginActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        javax.swing.JButton btnLogin;
        javax.swing.JLabel jLabel2;
        javax.swing.JLabel jLabel3;
        javax.swing.JPanel jPanel1;
        javax.swing.JPanel jPanel2;
        javax.swing.JTextField textFieldID;
        javax.swing.JPasswordField textFieldPassword;
        // End of variables declaration//GEN-END:variables
}
