/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sistemabsensi.ui.admin.ui;

import java.util.LinkedList;
import sistemabsensi.database.Shift;
import sistemabsensi.ui.admin.database.DatabaseAdmin;
import sistemabsensi.ui.admin.database.Jabatan;
import sistemabsensi.ui.admin.database.Karyawan;
import sistemabsensi.ui.admin.database.KolomPencarian;
import sistemabsensi.ui.admin.database.Prodi;

/**
 *
 * @author rss
 */
public class JPanelMasterDataKaryawan extends javax.swing.JPanel {

	/**
	 * Creates new form JPanelMasterDataKaryawan
	 */
	private DatabaseAdmin db;

	private Karyawan karyawanTerpilih = null;
	private Prodi prodiTerpilih = null;
	private Shift shiftTerpilih = null;
	private Jabatan jabatanTerpilih = null;
	private final JPanelMasterDataJabatan MasterDataJabatan;
	private final JPanelMasterDataProdi MasterDataProdi;
	private char defaultEchoChar;

	public JPanelMasterDataKaryawan(DatabaseAdmin db) {
		this.db = db;

		initComponents();
		this.defaultEchoChar = this.fieldPassword.getEchoChar();
		this.MasterDataProdi = new JPanelMasterDataProdi(db, this);
		this.MasterDataJabatan = new JPanelMasterDataJabatan(db, this);
		this.tabbedPane.add(this.MasterDataJabatan, "MasterData Jabatan");
		this.tabbedPane.add(this.MasterDataProdi, "MasterData Prodi");
		this.updateData();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jButton1 = new javax.swing.JButton();
                jPanel1 = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                tabelData = new javax.swing.JTable();
                jPanel9 = new javax.swing.JPanel();
                jLabel6 = new javax.swing.JLabel();
                textFieldID = new javax.swing.JTextField();
                jLabel1 = new javax.swing.JLabel();
                textFieldNama = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                comboBoxProdi = new javax.swing.JComboBox<>();
                jLabel2 = new javax.swing.JLabel();
                comboBoxJabatan = new javax.swing.JComboBox<>();
                jLabel7 = new javax.swing.JLabel();
                comboBoxShift = new javax.swing.JComboBox<Shift>();
                jLabel4 = new javax.swing.JLabel();
                textFieldTelp = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                textFieldAlamat = new javax.swing.JTextField();
                jLabel8 = new javax.swing.JLabel();
                textFieldEmail = new javax.swing.JTextField();
                tabbedPane = new javax.swing.JTabbedPane();
                jLabel9 = new javax.swing.JLabel();
                jPanel7 = new javax.swing.JPanel();
                textFieldPencarian = new javax.swing.JTextField();
                btnPencarian = new javax.swing.JButton();
                jPanel2 = new javax.swing.JPanel();
                cbxFilter_Id = new javax.swing.JCheckBox();
                cbxFilter_Nama = new javax.swing.JCheckBox();
                cbxFilter_Jabatan = new javax.swing.JCheckBox();
                cbxFilter_Shift = new javax.swing.JCheckBox();
                cbxFilter_Telp = new javax.swing.JCheckBox();
                cbxFilter_Alamat = new javax.swing.JCheckBox();
                cbxFilter_Email = new javax.swing.JCheckBox();
                cbxFilter_Prodi = new javax.swing.JCheckBox();
                cbxFilter_Semua = new javax.swing.JCheckBox();
                btnSimpan = new javax.swing.JButton();
                btnHapus = new javax.swing.JButton();
                chbx_isAdminUser = new javax.swing.JCheckBox();
                panelFieldPassword = new javax.swing.JPanel();
                jLabel10 = new javax.swing.JLabel();
                fieldPassword = new javax.swing.JPasswordField();
                btnLihatPassword = new javax.swing.JButton();

                jButton1.setText("jButton1");

                setMaximumSize(new java.awt.Dimension(991, 599));
                setPreferredSize(new java.awt.Dimension(991, 599));
                setLayout(new java.awt.BorderLayout());

                jPanel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                jPanel1.setLayout(null);

                tabelData.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                tabelData.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                tabelData.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                tabelData.setShowGrid(true);
                tabelData.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tabelDataMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(tabelData);

                jPanel1.add(jScrollPane1);
                jScrollPane1.setBounds(10, 480, 1000, 230);

                jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));

                jLabel6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                jLabel6.setText("ID");

                textFieldID.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

                jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                jLabel1.setLabelFor(textFieldNama);
                jLabel1.setText("NAMA");

                textFieldNama.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

                jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                jLabel3.setLabelFor(comboBoxProdi);
                jLabel3.setText("PRODI");

                comboBoxProdi.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                comboBoxProdi.setModel(new javax.swing.DefaultComboBoxModel<>());

                jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                jLabel2.setLabelFor(comboBoxJabatan);
                jLabel2.setText("JABATAN");

                comboBoxJabatan.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                comboBoxJabatan.setModel(new javax.swing.DefaultComboBoxModel<>());

                jLabel7.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                jLabel7.setText("SHIFT");

                comboBoxShift.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                comboBoxShift.setModel(new javax.swing.DefaultComboBoxModel<>());

                jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                jLabel4.setText("NO TELP/HP");

                textFieldTelp.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

                jLabel5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                jLabel5.setText("ALAMAT");

                textFieldAlamat.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

                jLabel8.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                jLabel8.setText("EMAIL");

                textFieldEmail.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

                javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
                jPanel9.setLayout(jPanel9Layout);
                jPanel9Layout.setHorizontalGroup(
                        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(textFieldNama, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(comboBoxProdi, javax.swing.GroupLayout.Alignment.LEADING, 0, 354, Short.MAX_VALUE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(comboBoxJabatan, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textFieldID)
                                        .addComponent(textFieldAlamat, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(comboBoxShift, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(textFieldEmail)
                                        .addComponent(textFieldTelp, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addContainerGap())
                );
                jPanel9Layout.setVerticalGroup(
                        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(comboBoxProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(comboBoxJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(comboBoxShift, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textFieldTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textFieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                );

                jPanel1.add(jPanel9);
                jPanel9.setBounds(14, 50, 480, 310);

                tabbedPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
                tabbedPane.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
                jPanel1.add(tabbedPane);
                tabbedPane.setBounds(540, 50, 770, 370);

                jLabel9.setFont(jLabel9.getFont().deriveFont((jLabel9.getFont().getStyle() | java.awt.Font.ITALIC) | java.awt.Font.BOLD, jLabel9.getFont().getSize()+11));
                jLabel9.setText("MAINTENENCE KARYAWAN");
                jPanel1.add(jLabel9);
                jLabel9.setBounds(100, 10, 320, 30);

                textFieldPencarian.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                textFieldPencarian.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                textFieldPencarianActionPerformed(evt);
                        }
                });

                btnPencarian.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                btnPencarian.setText("Cari");
                btnPencarian.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnPencarianActionPerformed(evt);
                        }
                });

                jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Kolom Pencarian"));
                jPanel2.setLayout(new java.awt.GridLayout(3, 3));

                cbxFilter_Id.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                cbxFilter_Id.setText("ID");
                jPanel2.add(cbxFilter_Id);

                cbxFilter_Nama.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                cbxFilter_Nama.setText("NAMA");
                jPanel2.add(cbxFilter_Nama);

                cbxFilter_Jabatan.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                cbxFilter_Jabatan.setText("JABATAN");
                jPanel2.add(cbxFilter_Jabatan);

                cbxFilter_Shift.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                cbxFilter_Shift.setText("SHIFT");
                jPanel2.add(cbxFilter_Shift);

                cbxFilter_Telp.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                cbxFilter_Telp.setText("NO TELP");
                jPanel2.add(cbxFilter_Telp);

                cbxFilter_Alamat.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                cbxFilter_Alamat.setText("ALAMAT");
                jPanel2.add(cbxFilter_Alamat);

                cbxFilter_Email.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                cbxFilter_Email.setText("EMAIL");
                jPanel2.add(cbxFilter_Email);

                cbxFilter_Prodi.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                cbxFilter_Prodi.setText("PRODI");
                jPanel2.add(cbxFilter_Prodi);

                cbxFilter_Semua.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                cbxFilter_Semua.setText("Semua");
                cbxFilter_Semua.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cbxFilter_SemuaActionPerformed(evt);
                        }
                });
                jPanel2.add(cbxFilter_Semua);

                javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
                jPanel7.setLayout(jPanel7Layout);
                jPanel7Layout.setHorizontalGroup(
                        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(btnPencarian)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textFieldPencarian)))
                                .addContainerGap())
                );
                jPanel7Layout.setVerticalGroup(
                        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnPencarian)
                                        .addComponent(textFieldPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );

                jPanel1.add(jPanel7);
                jPanel7.setBounds(1020, 480, 320, 240);

                btnSimpan.setBackground(new java.awt.Color(102, 255, 102));
                btnSimpan.setForeground(new java.awt.Color(0, 0, 0));
                btnSimpan.setText("SIMPAN");
                btnSimpan.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSimpanActionPerformed(evt);
                        }
                });
                jPanel1.add(btnSimpan);
                btnSimpan.setBounds(100, 430, 90, 38);

                btnHapus.setBackground(new java.awt.Color(255, 51, 51));
                btnHapus.setForeground(new java.awt.Color(0, 0, 0));
                btnHapus.setText("HAPUS");
                btnHapus.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnHapusActionPerformed(evt);
                        }
                });
                jPanel1.add(btnHapus);
                btnHapus.setBounds(10, 430, 90, 38);

                chbx_isAdminUser.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
                chbx_isAdminUser.setText("Adalah Admin");
                chbx_isAdminUser.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                chbx_isAdminUserActionPerformed(evt);
                        }
                });
                jPanel1.add(chbx_isAdminUser);
                chbx_isAdminUser.setBounds(190, 360, 150, 30);

                jLabel10.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                jLabel10.setText("PASSWORD");

                fieldPassword.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                fieldPassword.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                fieldPasswordActionPerformed(evt);
                        }
                });

                btnLihatPassword.setText("LIHAT");
                btnLihatPassword.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnLihatPasswordActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout panelFieldPasswordLayout = new javax.swing.GroupLayout(panelFieldPassword);
                panelFieldPassword.setLayout(panelFieldPasswordLayout);
                panelFieldPasswordLayout.setHorizontalGroup(
                        panelFieldPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelFieldPasswordLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLihatPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                panelFieldPasswordLayout.setVerticalGroup(
                        panelFieldPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelFieldPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnLihatPassword))
                );

                jPanel1.add(panelFieldPassword);
                panelFieldPassword.setBounds(30, 390, 470, 30);

                add(jPanel1, java.awt.BorderLayout.CENTER);
        }// </editor-fold>//GEN-END:initComponents

        private void tabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataMouseClicked
		int barisTerpilih = this.tabelData.getSelectedRow();
		String idKaryawan = (String) this.tabelData.getModel().getValueAt(barisTerpilih, 0);
		this.getDataTerpilih(idKaryawan);
        }//GEN-LAST:event_tabelDataMouseClicked

        private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
		// UPDATE OR INSERT

		if (!isFieldInputTerisiSemua()) {
			return;
		}

		Karyawan dataKaryawanField = dapatkanDataFieldInput();

		db.simpanDataKaryawan(dataKaryawanField);

		if (this.chbx_isAdminUser.isSelected() && !db.isKaryawanAdmin(dataKaryawanField.idKaryawan)) {
			db.tambahKaryawanAdmin(dataKaryawanField.idKaryawan, this.fieldPassword.getText());
		} else if (!this.chbx_isAdminUser.isSelected() && db.isKaryawanAdmin(dataKaryawanField.idKaryawan)) {
			db.hapusKaryawanAdmin(dataKaryawanField.idKaryawan);
		}

		this.updateData();
        }//GEN-LAST:event_btnSimpanActionPerformed

        private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
		if (this.textFieldID.getText().isEmpty()) {
			this.textFieldID.requestFocus();
			DialogPesan.tampilPesan("Pastikan ID Terisi!");
			return;
		}

		if (!this.db.isDataKaryawanAda(this.textFieldID.getText())) {
			this.textFieldID.requestFocus();
			DialogPesan.tampilPesan("Tidak ditemukan data yang Ber-ID: " + this.textFieldID.getText() + ". Pastikan ID valid!");
			return;
		}

		if (!DialogPesan.tampilKonfirmasi("Konfirmasi Penghapusan Data",
			"Anda Yakin ingin menghapus Data karyawan Ber-ID: " + this.textFieldID.getText() + "?.")) {
			return;
		}

		this.db.deleteDataKaryawan(this.textFieldID.getText());

		this.updateData();
        }//GEN-LAST:event_btnHapusActionPerformed

        private void btnPencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPencarianActionPerformed
		if (this.textFieldPencarian.getText().isEmpty()) {
			this.textFieldPencarian.requestFocus();
			dapatkanData();
			DialogPesan.tampilPesan("Field Pencarian Masih Home!");
			return;
		}

		LinkedList<KolomPencarian> kolomPencarian = new LinkedList<>();

		if (this.cbxFilter_Id.isSelected()) {
			kolomPencarian.add(KolomPencarian.ID);
		}
		if (this.cbxFilter_Alamat.isSelected()) {
			kolomPencarian.add(KolomPencarian.ALAMAT);
		}
		if (this.cbxFilter_Email.isSelected()) {
			kolomPencarian.add(KolomPencarian.EMAIL);
		}
		if (this.cbxFilter_Jabatan.isSelected()) {
			kolomPencarian.add(KolomPencarian.JABATAN);
		}
		if (this.cbxFilter_Nama.isSelected()) {
			kolomPencarian.add(KolomPencarian.NAMA);
		}
		if (this.cbxFilter_Shift.isSelected()) {
			kolomPencarian.add(KolomPencarian.SHIFT);
		}
		if (this.cbxFilter_Telp.isSelected()) {
			kolomPencarian.add(KolomPencarian.NO_TELP);
		}
		if (this.cbxFilter_Prodi.isSelected()) {
			kolomPencarian.add(KolomPencarian.PRODI);
		}

		if (kolomPencarian.isEmpty()) {
			this.dapatkanData();
			DialogPesan.tampilPesan("Pilih Setidaknya Satu Target Kolom Untuk Pencarian");
			return;
		}

		
			this.tabelData.setModel(db.getModelTabel_PencarianKaryawan(this.textFieldPencarian.getText(), kolomPencarian));
			this.isiDataDataComboBox();
		
        }//GEN-LAST:event_btnPencarianActionPerformed

        private void textFieldPencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPencarianActionPerformed
		if (this.textFieldPencarian.getText().isEmpty())
			this.dapatkanData();
        }//GEN-LAST:event_textFieldPencarianActionPerformed

        private void cbxFilter_SemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFilter_SemuaActionPerformed
		boolean selected = this.cbxFilter_Semua.isSelected();
		cbxFilter_Alamat.setSelected(selected);
		cbxFilter_Email.setSelected(selected);
		cbxFilter_Id.setSelected(selected);
		cbxFilter_Jabatan.setSelected(selected);
		cbxFilter_Nama.setSelected(selected);
		cbxFilter_Prodi.setSelected(selected);
		cbxFilter_Semua.setSelected(selected);
		cbxFilter_Shift.setSelected(selected);
		cbxFilter_Telp.setSelected(selected);

        }//GEN-LAST:event_cbxFilter_SemuaActionPerformed

        private void chbx_isAdminUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbx_isAdminUserActionPerformed
		if (this.chbx_isAdminUser.isSelected()) {
			this.panelFieldPassword.setVisible(true);
		} else {
			this.panelFieldPassword.setVisible(false);
		}
        }//GEN-LAST:event_chbx_isAdminUserActionPerformed

        private void fieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPasswordActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_fieldPasswordActionPerformed

        private void btnLihatPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatPasswordActionPerformed
		if (this.fieldPassword.getEchoChar() != 0) {
			this.fieldPassword.setEchoChar((char) 0); // Show password
			this.btnLihatPassword.setText("SEMBUNYIKAN");
		} else {

			this.fieldPassword.setEchoChar(defaultEchoChar); // Hide password
			this.btnLihatPassword.setText("LIHAT");
		}
        }//GEN-LAST:event_btnLihatPasswordActionPerformed

	public void updateData() {
		this.karyawanTerpilih = null;
		this.prodiTerpilih = null;
		this.shiftTerpilih = null;
		this.jabatanTerpilih = null;
		this.textFieldAlamat.setText("");
		this.textFieldEmail.setText("");
		this.textFieldID.setText("");
		this.textFieldNama.setText("");
		this.textFieldTelp.setText("");
		this.chbx_isAdminUser.setSelected(false);
		this.panelFieldPassword.setVisible(false);
		dapatkanData();
	}

	private boolean isFieldInputTerisiSemua() {
		if (this.textFieldID.getText().isEmpty()) {
			textFieldID.requestFocus();
			DialogPesan.tampilPesan("ID Masih Home");
			return false;
		} else if (this.textFieldNama.getText().isEmpty()) {
			textFieldNama.requestFocus();
			DialogPesan.tampilPesan("Nama masih Home");
			return false;
		} else if (this.textFieldTelp.getText().isEmpty()) {
			this.textFieldTelp.requestFocus();
			DialogPesan.tampilPesan("Masukan Nomor Telpon Karyawan");
			return false;
		} else if (this.textFieldAlamat.getText().isEmpty()) {
			this.textFieldAlamat.requestFocus();
			DialogPesan.tampilPesan("Masukan Alamat Rumah Karyawan");
			return false;
		} else if (this.textFieldEmail.getText().isEmpty()) {
			this.textFieldEmail.requestFocus();
			DialogPesan.tampilPesan("Masukan Alamat Email Karyawan");
			return false;
		} else if (this.comboBoxJabatan.getSelectedItem() == null) {
			this.comboBoxJabatan.requestFocus();
			DialogPesan.tampilPesan("Tentukan Jabatan Karyawan");
			return false;
		} else if (this.comboBoxShift.getSelectedItem() == null) {
			this.comboBoxShift.requestFocus();
			DialogPesan.tampilPesan("Tentukan Shift Karyawan");
			return false;
		} else if (this.comboBoxProdi.getSelectedItem() == null) {
			this.comboBoxProdi.requestFocus();
			DialogPesan.tampilPesan("Tentukan Prodi Karyawan");
			return false;
		} else if (this.panelFieldPassword.isVisible() && this.fieldPassword.getText().isEmpty()) {
			this.fieldPassword.requestFocus();
			DialogPesan.tampilPesan("Isi Password Admin");
			return false;
		}

		return true;
	}

	private Karyawan dapatkanDataFieldInput() {
		Karyawan karyawan = new Karyawan();

		karyawan.idKaryawan = this.textFieldID.getText();
		karyawan.namaKaryawan = this.textFieldNama.getText();
		karyawan.alamat = this.textFieldAlamat.getText();
		karyawan.noTelepon = this.textFieldTelp.getText();
		karyawan.email = this.textFieldEmail.getText();

		final Jabatan jabatan = (Jabatan) this.comboBoxJabatan.getSelectedItem();
		final Prodi prodi = (Prodi) this.comboBoxProdi.getSelectedItem();
		final Shift shift = (Shift) this.comboBoxShift.getSelectedItem();

		karyawan.idJabatan = jabatan.idJabatan;
		karyawan.idShift = shift.idShift;
		karyawan.idProdi = prodi.id;

		return karyawan;
	}

	private void tampilkanDataTerpilih() {
		this.textFieldID.setText(this.karyawanTerpilih.idKaryawan);
		this.textFieldNama.setText(this.karyawanTerpilih.namaKaryawan);
		this.textFieldAlamat.setText(this.karyawanTerpilih.alamat);
		this.textFieldTelp.setText(this.karyawanTerpilih.noTelepon);
		this.textFieldEmail.setText(this.karyawanTerpilih.email);
		this.isiDataDataComboBox();
	}

	private void getDataTerpilih(String idKaryawan) {

		Object[] data = this.db.getDataKaryawan(idKaryawan);

		this.karyawanTerpilih = (Karyawan) data[0];
		this.prodiTerpilih = (Prodi) data[1];
		this.jabatanTerpilih = (Jabatan) data[2];
		this.shiftTerpilih = (Shift) data[3];

		this.fieldPassword.setText("");
		if (this.db.isKaryawanAdmin(this.karyawanTerpilih.idKaryawan)) {
			this.chbx_isAdminUser.setSelected(true);
			this.panelFieldPassword.setVisible(true);
			this.fieldPassword.setText(db.getPasswordKaryawanAdmin(this.karyawanTerpilih.idKaryawan));
		} else {
			this.chbx_isAdminUser.setSelected(false);
			this.panelFieldPassword.setVisible(false);

		}

		this.tampilkanDataTerpilih();
		this.isiDataDataComboBox();

	}

	private void isiDataComboBoxShift() {
		this.comboBoxShift.removeAllItems();

		LinkedList<Shift> dataShift = db.getDaftarDataShift();

		for (Shift shift : dataShift) {
			if (this.shiftTerpilih != null && this.shiftTerpilih.equals(shift)) {
				continue;
			}
			this.comboBoxShift.addItem(shift);
		}
		if (this.shiftTerpilih != null) {
			this.comboBoxShift.addItem(this.shiftTerpilih);
			this.comboBoxShift.setSelectedItem(this.shiftTerpilih);
		} else if (this.shiftTerpilih == null) {
			this.comboBoxShift.setSelectedItem(null);
		}

	}

	private void isiDataComboBoxJabatan() {
		this.comboBoxJabatan.removeAllItems();

		LinkedList<Jabatan> dataJabatan;
		dataJabatan = db.getDaftarDataJabatan();
		for (Jabatan jabatan : dataJabatan) {
			if (this.jabatanTerpilih != null && this.jabatanTerpilih.equals(jabatan)) {
				continue;
			}
			this.comboBoxJabatan.addItem(jabatan);
		}
		if (this.jabatanTerpilih != null) {
			this.comboBoxJabatan.addItem(this.jabatanTerpilih);
			this.comboBoxJabatan.setSelectedItem(this.jabatanTerpilih);
		} else if (this.jabatanTerpilih == null) {
			this.comboBoxJabatan.setSelectedItem(null);
		}

	}

	private void isiDataComboBoxProdi() {
		this.comboBoxProdi.removeAllItems();
		LinkedList<Prodi> dataProdi = db.getDaftarDataProdi();
		for (Prodi prodi : dataProdi) {
			if (this.prodiTerpilih != null && this.prodiTerpilih.equals(prodi)) {
				continue;
			}
			this.comboBoxProdi.addItem(prodi);
		}

		if (this.prodiTerpilih != null) {
			this.comboBoxProdi.addItem(this.prodiTerpilih);
			this.comboBoxProdi.setSelectedItem(this.prodiTerpilih);
		} else if (this.prodiTerpilih == null) {
			this.comboBoxProdi.setSelectedItem(null);
		}
	}

	private void isiDataDataComboBox() {
		this.isiDataComboBoxShift();
		this.isiDataComboBoxJabatan();
		this.isiDataComboBoxProdi();
	}

	private void dapatkanData() {
		this.tabelData.setModel(db.getModelTabel_Karyawan());
		this.isiDataDataComboBox();

	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnHapus;
        private javax.swing.JButton btnLihatPassword;
        private javax.swing.JButton btnPencarian;
        private javax.swing.JButton btnSimpan;
        private javax.swing.JCheckBox cbxFilter_Alamat;
        private javax.swing.JCheckBox cbxFilter_Email;
        private javax.swing.JCheckBox cbxFilter_Id;
        private javax.swing.JCheckBox cbxFilter_Jabatan;
        private javax.swing.JCheckBox cbxFilter_Nama;
        private javax.swing.JCheckBox cbxFilter_Prodi;
        private javax.swing.JCheckBox cbxFilter_Semua;
        private javax.swing.JCheckBox cbxFilter_Shift;
        private javax.swing.JCheckBox cbxFilter_Telp;
        private javax.swing.JCheckBox chbx_isAdminUser;
        private javax.swing.JComboBox<Jabatan> comboBoxJabatan;
        private javax.swing.JComboBox<Prodi> comboBoxProdi;
        private javax.swing.JComboBox<Shift> comboBoxShift;
        private javax.swing.JPasswordField fieldPassword;
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel7;
        private javax.swing.JPanel jPanel9;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JPanel panelFieldPassword;
        private javax.swing.JTabbedPane tabbedPane;
        private javax.swing.JTable tabelData;
        private javax.swing.JTextField textFieldAlamat;
        private javax.swing.JTextField textFieldEmail;
        private javax.swing.JTextField textFieldID;
        private javax.swing.JTextField textFieldNama;
        private javax.swing.JTextField textFieldPencarian;
        private javax.swing.JTextField textFieldTelp;
        // End of variables declaration//GEN-END:variables
}
